'use strict';

function overlayPageCsp() {
  return "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors *";
}

function renderOverlayPage(publicId, kind, name) {
  const boot = JSON.stringify({ publicId, kind, name }).replace(/</g, '\\u003c');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
  :root{--a:#ff75ac;--b:#9a57c4;--text:#fff;--muted:rgba(255,255,255,.7)}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;font-family:Segoe UI,Arial,sans-serif;color:var(--text)}body{padding:14px}.hidden{display:none!important}.card{width:min(680px,100%);padding:18px;border-radius:22px;background:linear-gradient(135deg,rgba(20,13,33,.94),rgba(49,25,68,.91));border:1px solid color-mix(in srgb,var(--a) 38%,transparent);box-shadow:0 18px 55px rgba(0,0,0,.42),0 0 28px color-mix(in srgb,var(--a) 22%,transparent);backdrop-filter:blur(16px)}.head,.row,.meta{display:flex;align-items:center;justify-content:space-between;gap:12px}.head{margin-bottom:13px}.head strong{font-size:22px}.badge{padding:6px 10px;border-radius:999px;background:color-mix(in srgb,var(--a) 20%,transparent);border:1px solid color-mix(in srgb,var(--a) 42%,transparent);font-size:11px;font-weight:850}.now,.row,.gift-box{padding:11px 13px;border-radius:15px;background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.09)}.now{margin-bottom:9px}.now strong,.now small,.row strong,.row small{display:block}.now small,.row small,.empty{color:var(--muted)}.queue,.ranking-list{display:grid;gap:8px}.rank{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(135deg,var(--a),var(--b));font-weight:900}.row-copy{flex:1;min-width:0}.value{white-space:nowrap}.progress{height:14px;border-radius:999px;background:rgba(255,255,255,.09);overflow:hidden}.progress span{display:block;height:100%;background:linear-gradient(90deg,var(--a),var(--b));transition:width .4s ease}.gift-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.empty{text-align:center;padding:20px}.screen{position:fixed;inset:0;display:grid;place-items:center;padding:3vh}.screen img{display:none;max-width:94vw;max-height:94vh;object-fit:contain;filter:drop-shadow(0 18px 38px rgba(0,0,0,.4));animation:appear .22s ease both}@keyframes appear{from{opacity:0;transform:scale(.88)}to{opacity:1;transform:scale(1)}}@media(max-width:480px){.gift-grid{grid-template-columns:1fr}.card{padding:14px}}
  .card{animation:overlay-enter .4s cubic-bezier(.2,.85,.25,1) both}.rank{animation:rank-float 2.2s ease-in-out infinite alternate}.row:nth-child(2n) .rank{animation-delay:.18s}.progress span{background-size:200% 100%;animation:progress-flow 2.2s linear infinite}.gift-box{animation:gift-float 2.5s ease-in-out infinite alternate}.gift-box:nth-child(2){animation-delay:.2s}@keyframes overlay-enter{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:none}}@keyframes rank-float{to{transform:translateY(-3px);box-shadow:0 0 18px color-mix(in srgb,var(--a) 26%,transparent)}}@keyframes progress-flow{to{background-position:200% 0}}@keyframes gift-float{to{transform:translateY(-4px);border-color:rgba(255,255,255,.18)}}@media(prefers-reduced-motion:reduce){.card,.rank,.progress span,.gift-box{animation:none!important}}
  </style></head><body><main id="root"></main><script>
  'use strict';const boot=${boot},root=document.getElementById('root');let last='',hideTimer=0;
  const text=(value,fallback='')=>String(value??fallback),node=(tag,className,value)=>{const element=document.createElement(tag);if(className)element.className=className;if(value!==undefined)element.textContent=text(value);return element};
  const themeMap={lulu:['#ff75ac','#9a57c4'],pink:['#ff75ac','#9a57c4'],purple:['#ae5eff','#694fe0'],blue:['#469dff','#7058e8'],mint:['#25f4ee','#2ec3c0'],miku:['#25f4ee','#ff75ac'],red:['#ff4c69','#bb2748'],gold:['#ffd166','#ff7b54']};
  function setTheme(value){const colors=themeMap[text(value).toLowerCase()]||themeMap.lulu;document.documentElement.style.setProperty('--a',colors[0]);document.documentElement.style.setProperty('--b',colors[1])}
  function header(title,badge='LIVE'){const head=node('div','head');head.append(node('strong','',title),node('span','badge',badge));return head}
  function card(title,badge){const box=node('section','card');box.append(header(title,badge));return box}
  function renderPlaylist(data){const box=card('Lista de reproducción',data.provider||'Música');if(data.current){const now=node('div','now');now.append(node('strong','',data.current.title||'Canción actual'),node('small','',data.current.requestedBy?'Solicitada por '+data.current.requestedBy:'Reproduciendo ahora'));box.append(now)}else box.append(node('div','empty','No hay una canción reproduciéndose.'));const queue=node('div','queue');(Array.isArray(data.queue)?data.queue:[]).slice(0,5).forEach((item,index)=>{const row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','',item.title||'Canción'),node('small','',item.requestedBy?'Pedida por '+item.requestedBy:'Solicitud manual'));row.append(node('span','rank',index+1),copy);queue.append(row)});box.append(queue);root.replaceChildren(box)}
  function renderWallet(data){const box=card(data.displayName||data.user||'Esperando usuario','SALDO'),row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','',data.user?'@'+data.user:'Último saldo'),node('small','',data.currencyName||'Lunitas'));row.append(copy,node('strong','value',(data.currencySymbol||'🌙')+' '+Number(data.balance||0).toLocaleString('es-MX')));box.append(row);root.replaceChildren(box)}
  function renderGame(data){const box=card(data.title||'Juegos del LIVE',text(data.status||'esperando').toUpperCase());box.append(node('div','now',data.detail||data.text||'Esperando una partida.'));const meta=node('div','meta');meta.append(node('span','',data.displayName||data.user||'Esperando jugador'),node('strong','',(data.currencySymbol||'🌙')+' '+Number(data.payout||0).toLocaleString('es-MX')));box.append(meta);root.replaceChildren(box)}
  function renderAlert(data){const box=card(data.title||'Alertas de Lulu',data.icon||'✦');box.append(node('div','now',data.text||'Esperando un evento del LIVE.'));root.replaceChildren(box)}
  function renderGoal(data){const target=Math.max(1,Number(data.target||1)),progress=Math.max(0,Number(data.progress||0)),percent=Math.max(0,Math.min(100,Number(data.percent??progress/target*100))),box=card(data.title||'Meta del LIVE',Math.round(percent)+'%'),track=node('div','progress');track.append(node('span'));track.firstChild.style.width=percent+'%';box.append(track);const meta=node('div','meta');meta.append(node('strong','',data.text||progress.toLocaleString('es-MX')+' / '+target.toLocaleString('es-MX')),node('small','',text(data.goalType||'meta').toUpperCase()));box.append(meta);root.replaceChildren(box)}
  function renderGift(data){const box=card('Regalos del LIVE',Number(data.totalGifts||0).toLocaleString('es-MX')+' regalos'),grid=node('div','gift-grid');for(const [label,gift] of [['TOP REGALO',data.topGift],['MEJOR RACHA',data.topStreak]]){const item=node('div','gift-box'),value=gift||{};item.append(node('small','',label),node('strong','',value.displayName||'Esperando'),node('div','',value.giftName?value.giftName+' ×'+Number(value.repeatCount||1):'—'));grid.append(item)}box.append(grid);root.replaceChildren(box)}
  function renderRanking(data){const config=data.config||data,box=card(config.title||'RANKING',text(config.type||'LIVE').toUpperCase()),list=node('div','ranking-list'),entries=Array.isArray(data.entries)?data.entries:[];if(!entries.length)list.append(node('div','empty','Esperando datos del LIVE…'));entries.slice(0,10).forEach((entry,index)=>{const row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','',entry.displayName||entry.user||'Usuario'),node('small','',entry.user?'@'+entry.user:''));row.append(node('span','rank',index+1),copy,node('strong','value',Number(entry.value||0).toLocaleString('es-MX')));list.append(row)});box.append(list);root.replaceChildren(box)}
  function renderScreen(data){clearTimeout(hideTimer);const stage=node('div','screen');if(data.type==='show'&&data.url&&(!data.expiresAt||Number(data.expiresAt)>Date.now())){const image=node('img');image.alt='';image.src=data.url;image.onload=()=>{image.style.display='block'};stage.append(image);if(data.expiresAt)hideTimer=setTimeout(()=>root.replaceChildren(),Math.max(0,Number(data.expiresAt)-Date.now()))}root.replaceChildren(stage)}
  function render(data){setTheme(data.theme);if(boot.kind==='ranking')renderRanking(data);else if(boot.kind==='screen')renderScreen(data);else if(boot.name==='wallet')renderWallet(data);else if(boot.name==='game')renderGame(data);else if(boot.name==='alert')renderAlert(data);else if(boot.name==='goal')renderGoal(data);else if(boot.name==='gift')renderGift(data);else renderPlaylist(data)}
  async function poll(){try{const url='/v1/overlays/'+encodeURIComponent(boot.publicId)+'/sources/'+encodeURIComponent(boot.kind)+'/'+encodeURIComponent(boot.name),response=await fetch(url,{cache:'no-store'});if(response.ok){const raw=await response.text();if(raw!==last){last=raw;render(JSON.parse(raw).data||{})}}}catch{}setTimeout(poll,700)}poll();
  </script></body></html>`;
}

module.exports = { overlayPageCsp, renderOverlayPage };
