'use strict';
const widgetDesignScript = require('fs').readFileSync(require('path').join(__dirname, 'widget-design.js'), 'utf8');

function overlayPageCsp() {
  return "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors *";
}

function renderOverlayPage(publicId, kind, name) {
  const boot = JSON.stringify({ publicId, kind, name }).replace(/</g, '\\u003c');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
  :root{--a:#ff75ac;--b:#9a57c4;--text:#fff;--muted:rgba(255,255,255,.7);--card-bg:linear-gradient(135deg,rgba(20,13,33,.94),rgba(49,25,68,.91));--radius:22px;--goal-height:14px}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;font-family:Segoe UI,Arial,sans-serif;color:var(--text)}body{padding:14px}.hidden{display:none!important}.card{position:relative;width:min(680px,100%);padding:18px;overflow:hidden;border-radius:var(--radius);color:var(--text);background:var(--card-bg);border:1px solid color-mix(in srgb,var(--a) 38%,transparent);box-shadow:0 18px 55px rgba(0,0,0,.42),0 0 28px color-mix(in srgb,var(--a) 18%,transparent);backdrop-filter:blur(16px)}.card:before{content:"";position:absolute;inset:0 0 auto;height:3px;background:linear-gradient(90deg,var(--a),var(--b))}.card>*{position:relative;z-index:1}.head,.row,.meta{display:flex;align-items:center;justify-content:space-between;gap:12px}.head{margin-bottom:13px}.head strong{font-size:22px}.badge{padding:6px 10px;border-radius:999px;background:color-mix(in srgb,var(--a) 20%,transparent);border:1px solid color-mix(in srgb,var(--a) 42%,transparent);font-size:11px;font-weight:850}.now,.row,.gift-box{padding:11px 13px;border-radius:15px;background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.09)}.now{margin-bottom:9px}.now strong,.now small,.row strong,.row small{display:block}.now small,.row small,.empty{color:var(--muted)}.queue,.ranking-list{display:grid;gap:8px}.rank{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(135deg,var(--a),var(--b));font-weight:900}.row-copy{flex:1;min-width:0}.value{white-space:nowrap}.progress{height:var(--goal-height);border-radius:999px;background:rgba(255,255,255,.09);overflow:hidden}.progress span{display:block;height:100%;background:linear-gradient(90deg,var(--a),var(--b))}.gift-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.empty{text-align:center;padding:20px}.screen{position:fixed;inset:0;display:grid;place-items:center;padding:3vh}.screen img{display:none;max-width:94vw;max-height:94vh;object-fit:contain;filter:drop-shadow(0 18px 38px rgba(0,0,0,.4))}@media(max-width:480px){.gift-grid{grid-template-columns:1fr}.card{padding:14px}}
  </style><style id="widget-design"></style></head><body><main id="root"></main><script>
  ${widgetDesignScript}
  'use strict';const boot=${boot},root=document.getElementById('root');let last='',hideTimer=0;
  const text=(value,fallback='')=>String(value??fallback),node=(tag,className,value)=>{const element=document.createElement(tag);if(className)element.className=className;if(value!==undefined)element.textContent=text(value);return element};
  const themeMap={lulu:['#ff67ad','#5fe8ff'],pink:['#ff75ac','#9a57c4'],purple:['#ae5eff','#694fe0'],blue:['#469dff','#7058e8'],mint:['#25f4ee','#2ec3c0'],miku:['#39f1d2','#ff68a9'],red:['#ff4c69','#bb2748'],gold:['#ffd56a','#d99832'],aurora:['#71ffd6','#9782ff'],cyber:['#00f6ff','#ff2bd6'],arcade:['#75ff4d','#ff3dd1'],hologram:['#80fff4','#ff80eb'],sakura:['#ff9fc9','#c79bff'],lavender:['#c7a0ff','#ff91cf'],sunset:['#ff7657','#ff3f9f'],ocean:['#48c8ff','#4267ff'],vampire:['#ff365f','#9e38ff'],mono:['#ffffff','#9da7b8']};
  const backgroundMap={plain:'linear-gradient(135deg,rgba(20,16,31,.96),rgba(49,31,61,.94))',stars:'radial-gradient(circle at 15% 20%,#fff 0 1px,transparent 2px),radial-gradient(circle at 75% 35%,var(--b) 0 1px,transparent 2px),linear-gradient(145deg,#07091e,#271443)',aurora:'radial-gradient(ellipse at 15% 20%,color-mix(in srgb,var(--a) 42%,transparent),transparent 48%),radial-gradient(ellipse at 86% 78%,color-mix(in srgb,var(--b) 42%,transparent),transparent 48%),#102038',grid:'linear-gradient(color-mix(in srgb,var(--a) 18%,transparent) 1px,transparent 1px),linear-gradient(90deg,color-mix(in srgb,var(--b) 18%,transparent) 1px,transparent 1px),#11172b',glass:'radial-gradient(circle at 15% 10%,rgba(255,255,255,.22),transparent 34%),radial-gradient(circle at 90% 88%,color-mix(in srgb,var(--b) 32%,transparent),transparent 45%),#39334c',bubbles:'radial-gradient(circle at 22% 72%,color-mix(in srgb,var(--a) 34%,transparent) 0 18px,transparent 19px),radial-gradient(circle at 75% 28%,color-mix(in srgb,var(--b) 34%,transparent) 0 25px,transparent 26px),#241935',vinyl:'radial-gradient(circle at 18% 50%,var(--a) 0 4px,#08080d 5px 13px,rgba(255,255,255,.16) 14px 15px,#08080d 16px 35px,transparent 36px),linear-gradient(135deg,#0c0c14,#251533)',pixel:'conic-gradient(from 90deg at 1px 1px,color-mix(in srgb,var(--a) 22%,transparent) 25%,transparent 0) 0 0/18px 18px,conic-gradient(from 270deg at 9px 9px,color-mix(in srgb,var(--b) 18%,transparent) 25%,transparent 0) 0 0/18px 18px,#130d31',waves:'repeating-radial-gradient(ellipse at 0 100%,transparent 0 18px,color-mix(in srgb,var(--a) 20%,transparent) 19px 21px,transparent 22px 37px,color-mix(in srgb,var(--b) 18%,transparent) 38px 40px),#102238',confetti:'linear-gradient(115deg,transparent 75%,color-mix(in srgb,var(--a) 48%,transparent) 76% 81%,transparent 82%) 0 0/42px 38px,linear-gradient(25deg,transparent 72%,color-mix(in srgb,var(--b) 45%,transparent) 73% 79%,transparent 80%) 8px 7px/52px 46px,#2b1735',spotlight:'radial-gradient(ellipse at 18% -10%,color-mix(in srgb,var(--a) 52%,transparent),transparent 54%),radial-gradient(ellipse at 88% -10%,color-mix(in srgb,var(--b) 48%,transparent),transparent 52%),linear-gradient(#282238,#090a12)',midnight:'radial-gradient(circle at 18% 20%,#fff 0 1px,transparent 2px),radial-gradient(circle at 68% 34%,rgba(255,255,255,.65) 0 1px,transparent 2px),radial-gradient(circle at 48% 78%,var(--b) 0 1px,transparent 2px),linear-gradient(155deg,#030714,#190d38)'};
  const color=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(text(value))?text(value).toLowerCase():fallback,limit=(value,min,max,fallback)=>{const number=Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,number)):fallback};
  const hideRoot=()=>{clearTimeout(hideTimer);hideTimer=0;root.replaceChildren()};
  const timedActivityVisible=(data,ready)=>{const expiresAt=Number(data.expiresAt||0);return data.visible!==false&&Boolean(ready)&&expiresAt>Date.now()};
  const armActivityExpiry=(data)=>{const expiresAt=Number(data.expiresAt||0);if(expiresAt>Date.now())hideTimer=setTimeout(hideRoot,Math.max(250,expiresAt-Date.now()))};
  function applyAppearance(data){document.getElementById('widget-design').textContent=LuluWidgetDesign.css(data.style||{});const config=data.config||{},colors=themeMap[text(data.theme).toLowerCase()]||themeMap.lulu;let a=color(config.accentColor,colors[0]),b=color(config.secondaryColor,colors[1]),foreground=color(config.textColor,'#ffffff'),background=backgroundMap[text(data.background).toLowerCase()]||backgroundMap.plain,radius=22,goalHeight=14;const style=data.style&&typeof data.style==='object'?data.style:null;if(style?.enabled===true){a=color(style.primaryColor,a);b=color(style.secondaryColor,b);foreground=color(style.textColor,foreground);const hex=color(style.backgroundColor,'#14101f'),opacity=limit(style.backgroundOpacity,0,100,94)/100,red=parseInt(hex.slice(1,3),16),green=parseInt(hex.slice(3,5),16),blue=parseInt(hex.slice(5,7),16);background='rgba('+red+','+green+','+blue+','+opacity+')';radius=limit(style.borderRadius,0,48,22);goalHeight=limit(style.goalBarHeight,4,40,14)}else if(boot.kind==='ranking'&&config.backgroundColor){const hex=color(config.backgroundColor,'#101018'),opacity=limit(config.backgroundOpacity,0,100,82)/100,red=parseInt(hex.slice(1,3),16),green=parseInt(hex.slice(3,5),16),blue=parseInt(hex.slice(5,7),16);background='rgba('+red+','+green+','+blue+','+opacity+')'}const rootStyle=document.documentElement.style;rootStyle.setProperty('--a',a);rootStyle.setProperty('--b',b);rootStyle.setProperty('--text',foreground);rootStyle.setProperty('--card-bg',background);rootStyle.setProperty('--radius',radius+'px');rootStyle.setProperty('--goal-height',goalHeight+'px')}
  function header(title,badge='LIVE'){const head=node('div','head');head.append(node('strong','',title),node('span','badge',badge));return head}
  function card(title,badge){const box=node('section','card');box.append(header(title,badge));return box}
  function renderPlaylist(data){clearTimeout(hideTimer);const items=Array.isArray(data.queue)?data.queue:[];if(data.visible===false||(!data.current&&!items.length)){hideRoot();return}const box=card('Lista de reproducción',data.provider||'Música');if(data.current){const now=node('div','now');now.append(node('strong','',data.current.title||'Canción actual'),node('small','',data.current.requestedBy?'Solicitada por '+data.current.requestedBy:'Reproduciendo ahora'));box.append(now)}else box.append(node('div','empty','Preparando la canción solicitada…'));const queue=node('div','queue');items.slice(0,5).forEach((item,index)=>{const row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','',item.title||'Canción'),node('small','',item.requestedBy?'Pedida por '+item.requestedBy:'Solicitud manual'));row.append(node('span','rank',index+1),copy);queue.append(row)});box.append(queue);root.replaceChildren(box)}
  function renderWallet(data){hideRoot();if(!timedActivityVisible(data,data.user))return;const box=card(data.displayName||data.user,'SALDO'),row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','','@'+data.user),node('small','',data.currencyName||'Lunitas'));row.append(copy,node('strong','value',(data.currencySymbol||'🌙')+' '+Number(data.balance||0).toLocaleString('es-MX')));box.append(row);root.replaceChildren(box);armActivityExpiry(data)}
  function renderGame(data){hideRoot();if(!timedActivityVisible(data,data.user&&data.status&&data.status!=='idle'))return;const box=card(data.title||'Juegos del LIVE',text(data.status).toUpperCase());box.append(node('div','now',data.detail||data.text||'Partida activa'));const meta=node('div','meta');meta.append(node('span','',data.displayName||data.user),node('strong','',(data.currencySymbol||'🌙')+' '+Number(data.payout||0).toLocaleString('es-MX')));box.append(meta);root.replaceChildren(box);armActivityExpiry(data)}
  function renderAlert(data){hideRoot();if(!timedActivityVisible(data,data.text))return;const box=card(data.title||'Alertas de Lulu',data.icon||'✦');box.append(node('div','now',data.text));root.replaceChildren(box);armActivityExpiry(data)}
  function renderGoal(data){clearTimeout(hideTimer);if(data.visible===false||!data.title){hideRoot();return}const target=Math.max(1,Number(data.target||1)),progress=Math.max(0,Number(data.progress||0)),percent=Math.max(0,Math.min(100,Number(data.percent??progress/target*100))),box=card(data.title,Math.round(percent)+'%'),track=node('div','progress');track.append(node('span'));track.firstChild.style.width=percent+'%';box.append(track);const meta=node('div','meta');meta.append(node('strong','',data.text||progress.toLocaleString('es-MX')+' / '+target.toLocaleString('es-MX')),node('small','',text(data.goalType||'meta').toUpperCase()));box.append(meta);root.replaceChildren(box)}
  function renderGift(data){hideRoot();if(!timedActivityVisible(data,data.lastGift))return;const box=card('Regalos del LIVE',Number(data.totalGifts||0).toLocaleString('es-MX')+' regalos'),grid=node('div','gift-grid');for(const [label,gift] of [['TOP REGALO',data.topGift],['MEJOR RACHA',data.topStreak]]){const item=node('div','gift-box'),value=gift||{};item.append(node('small','',label),node('strong','',value.displayName||'Esperando'),node('div','',value.giftName?value.giftName+' ×'+Number(value.repeatCount||1):'—'));grid.append(item)}box.append(grid);root.replaceChildren(box);armActivityExpiry(data)}
  function renderRanking(data){const config=data.config||data,box=card(config.title||'RANKING',text(config.type||'LIVE').toUpperCase()),list=node('div','ranking-list'),entries=Array.isArray(data.entries)?data.entries:[];if(!entries.length)list.append(node('div','empty','Esperando datos del LIVE…'));entries.slice(0,10).forEach((entry,index)=>{const row=node('div','row'),copy=node('div','row-copy');copy.append(node('strong','',entry.displayName||entry.user||'Usuario'),node('small','',entry.user?'@'+entry.user:''));row.append(node('span','rank',index+1),copy,node('strong','value',Number(entry.value||0).toLocaleString('es-MX')));list.append(row)});box.append(list);root.replaceChildren(box)}
  function renderScreen(data){clearTimeout(hideTimer);const stage=node('div','screen');if(data.type==='show'&&data.url&&(!data.expiresAt||Number(data.expiresAt)>Date.now())){const image=node('img');image.alt='';image.src=data.url;image.onload=()=>{image.style.display='block'};stage.append(image);if(data.expiresAt)hideTimer=setTimeout(()=>root.replaceChildren(),Math.max(0,Number(data.expiresAt)-Date.now()))}root.replaceChildren(stage)}
  function render(data){applyAppearance(data);if(boot.kind==='ranking')renderRanking(data);else if(boot.kind==='screen')renderScreen(data);else if(boot.name==='wallet')renderWallet(data);else if(boot.name==='game')renderGame(data);else if(boot.name==='alert')renderAlert(data);else if(boot.name==='goal')renderGoal(data);else if(boot.name==='gift')renderGift(data);else renderPlaylist(data)}
  async function poll(){try{const url='/v1/overlays/'+encodeURIComponent(boot.publicId)+'/sources/'+encodeURIComponent(boot.kind)+'/'+encodeURIComponent(boot.name),response=await fetch(url,{cache:'no-store'});if(response.ok){const raw=await response.text();if(raw!==last){last=raw;render(JSON.parse(raw).data||{})}}}catch{}setTimeout(poll,700)}poll();
  </script></body></html>`;
}

module.exports = { overlayPageCsp, renderOverlayPage };
